services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db_solar-watch
    environment:
      - POSTGRES_DB=solar-watch
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  backend:
    image: 'solarwatch-backend-image:latest'
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: solar-watch-backend
    depends_on:
      - db
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - JWT_SECRET=${JWT_SECRET}
      - OPEN_WEATHER_API_KEY=${OPEN_WEATHER_API_KEY}
      - JWT_EXP=${JWT_EXP}
      - SPRING_SQL_INIT_MODE=always
      - SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION=true


  frontend:
    image: 'solarwatch-frontend:latest'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: solar-watch-frontend
    depends_on:
      - backend
    ports:
      - "5173:3111"