services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db_solar-watch
    environment:
      - POSTGRES_DB=solar-watch
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  backend:
    image: 'solarwatch-backend-image:latest'
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=${JWT_SECRET}
      - API_KEY=${OPEN_WEATHER_API_KEY}
      - JWT_EXPIRATION_MS=${JWT_EXP}
      - SPRING_SQL_INIT_MODE=always
      - SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION=true


  frontend:
    image: 'solarwatch-frontend-image:latest'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      - BACKEND_HOST=backend